### ISSUE TITLE
Whole PC or maybe just the video card adapter freezes for a second every few seconds

### ISSUE THREAD

**Issue by Saya47** [RSIP-Vision/vscode-nividia-smi-plus#13]
Hello my mouse freezes every few seconds for a second, I tracked down the issue and when I disable your extension in VS Code problem goes away. I have installed the extension on WSL 2 on Windows 11.
Here are the settings that I use:
![image](https://github.com/RSIP-Vision/vscode-nividia-smi-plus/assets/35542834/13620c96-485f-4a11-a19a-3178d63251de)
The 61% in front of GPU name is Fan speed btw.

**Comment by Saya47** [comment]
Look at the spikes caused by the extension:
![image](https://github.com/RSIP-Vision/vscode-nividia-smi-plus/assets/35542834/844309a4-dfed-415d-964c-1ca70ef99bf9)

**Comment by Saya47** [comment]
I profiled the extension and found out it's the spawn process that's causing the issue. Turns out on WSL2, persistence mode is enabled by default on the GPU which means `nvidia-smi -q -x` will output smoothly but on Windows, persistence mode is not available, so the command causes the freezes.

**Comment by elazarcoh** [comment]
Thanks for the resolution ☺️
